
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 15 01:24:24 CET 2010
//----------------------------------------------------

package dflat.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LPARENT = 27;
  public static final int RPARENT = 26;
  public static final int DIVIDE = 43;
  public static final int DEC_INT_LITERAL = 4;
  public static final int STRING_LITERAL = 3;
  public static final int LTE = 33;
  public static final int RET = 13;
  public static final int PERIOD = 29;
  public static final int NOT_EQUAL = 36;
  public static final int INTEGER = 7;
  public static final int EXCLAM = 28;
  public static final int SEMI = 23;
  public static final int MINUS = 42;
  public static final int REF = 14;
  public static final int AND = 39;
  public static final int LT = 31;
  public static final int OR = 40;
  public static final int COMMA = 30;
  public static final int CLASS = 10;
  public static final int MULTIPLY = 44;
  public static final int PLUS = 41;
  public static final int ASSIGN = 20;
  public static final int IF = 15;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 21;
  public static final int EQUAL = 35;
  public static final int TRUE = 37;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int GTE = 34;
  public static final int NAME = 2;
  public static final int LBRACK = 25;
  public static final int ELSE = 17;
  public static final int FUNC = 11;
  public static final int RBRACK = 24;
  public static final int WHILE = 18;
  public static final int FLOAT = 9;
  public static final int THEN = 16;
  public static final int STATEMENT = 46;
  public static final int STRING = 8;
  public static final int FALSE = 38;
  public static final int FLOAT_LITERAL = 5;
  public static final int GT = 32;
  public static final int VAR = 12;
  public static final int EXPONENT = 45;
  public static final int DO = 19;
}

