
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 11 22:59:38 CET 2010
//----------------------------------------------------

package dflat.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RPARENT = 15;
  public static final int INTEGER = 4;
  public static final int RET = 10;
  public static final int FUNC = 8;
  public static final int BOOLEAN = 3;
  public static final int SEMI = 12;
  public static final int EOF = 0;
  public static final int STRING = 5;
  public static final int VAR = 9;
  public static final int RBRACK = 13;
  public static final int error = 1;
  public static final int REF = 11;
  public static final int LBRACK = 14;
  public static final int LPARENT = 16;
  public static final int FLOAT = 6;
  public static final int NAME = 2;
  public static final int CLASS = 7;
}

