
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 25 15:37:38 CEST 2010
//----------------------------------------------------

package dflat.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LPARENT = 28;
  public static final int RPARENT = 27;
  public static final int DIVIDE = 44;
  public static final int DEC_INT_LITERAL = 4;
  public static final int STRING_LITERAL = 3;
  public static final int LTE = 34;
  public static final int RET = 14;
  public static final int PERIOD = 30;
  public static final int NOT_EQUAL = 37;
  public static final int INTEGER = 8;
  public static final int EXCLAM = 29;
  public static final int SEMI = 24;
  public static final int MINUS = 43;
  public static final int REF = 15;
  public static final int AND = 40;
  public static final int LT = 32;
  public static final int OR = 41;
  public static final int COMMA = 31;
  public static final int CLASS = 11;
  public static final int MULTIPLY = 45;
  public static final int PLUS = 42;
  public static final int ASSIGN = 21;
  public static final int IF = 16;
  public static final int EOF = 0;
  public static final int BOOLEAN = 7;
  public static final int RETURN = 22;
  public static final int EQUAL = 36;
  public static final int TRUE = 38;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int NULL = 6;
  public static final int GTE = 35;
  public static final int NAME = 2;
  public static final int LBRACK = 26;
  public static final int ELSE = 18;
  public static final int FUNC = 12;
  public static final int RBRACK = 25;
  public static final int WHILE = 19;
  public static final int FLOAT = 10;
  public static final int THEN = 17;
  public static final int STRING = 9;
  public static final int FALSE = 39;
  public static final int FLOAT_LITERAL = 5;
  public static final int GT = 33;
  public static final int VAR = 13;
  public static final int EXPONENT = 46;
  public static final int DO = 20;
}

